---
- name: optionally run versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: install iperf
  ansible.builtin.include_tasks: install.yml

- name: create iperf user
  ansible.builtin.include_tasks: user.yml

- name: run systemd service
  ansible.builtin.include_tasks: systemd.yml
