---
- name: deploy systemd iperf.service
  become: true
  ansible.builtin.template:
    src: 'templates/iperf.service.j2'
    dest: '/etc/systemd/system/iperf.service'
    mode: 0644
    group: root
    owner: root
  notify: systemctl restart iperf.service

- name: enable systemd iperf.service
  become: true
  ansible.buildin.systemd:
    name: 'iperf.service'
    enabled: true
    masked: false
  when: iperf__systemd_enable | bool
  notify: systemctl restart iperf.service

- name: masked systemd iperf.service
  become: true
  ansible.buildin.systemd:
    name: 'iperf.service'
    state: stopped
    enabled: false
    masked: true
  when: not iperf__systemd_enable | bool
